# Table of Contents
 <p><div class="lev1 toc-item"><a href="#循环神经网络" data-toc-modified-id="循环神经网络-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>循环神经网络 </a></div><div class="lev2 toc-item"><a href="#Softmax-与交叉熵" data-toc-modified-id="Softmax-与交叉熵-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Softmax 与交叉熵 </a></div><div class="lev3 toc-item"><a href="#Sigmoid" data-toc-modified-id="Sigmoid-111"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Sigmoid</a></div><div class="lev2 toc-item"><a href="#2-class-Softmax" data-toc-modified-id="2-class-Softmax-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>2-class Softmax</a></div><div class="lev3 toc-item"><a href="#k-class-Softmax" data-toc-modified-id="k-class-Softmax-121"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>k-class Softmax</a></div><div class="lev2 toc-item"><a href="#Word-Embedding-+-Softmax-计算量" data-toc-modified-id="Word-Embedding-+-Softmax-计算量-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Word Embedding + Softmax 计算量 </a></div><div class="lev3 toc-item"><a href="#FLOPs" data-toc-modified-id="FLOPs-131"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>FLOPs</a></div><div class="lev3 toc-item"><a href="#FLOPs-Code" data-toc-modified-id="FLOPs-Code-132"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>FLOPs Code</a></div><div class="lev3 toc-item"><a href="#评估/小结" data-toc-modified-id="评估/小结-133"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>评估 / 小结 </a></div><div class="lev3 toc-item"><a href="#作业1" data-toc-modified-id="作业1-134"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>作业 1</a></div><div class="lev3 toc-item"><a href="#Softmax-优化：降低-k-和-V" data-toc-modified-id="Softmax-优化：降低-k-和-V-135"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Softmax 优化：降低 k 和 V</a></div><div class="lev4 toc-item"><a href="#纠错" data-toc-modified-id="纠错-1351"><span class="toc-item-num">1.3.5.1&nbsp;&nbsp;</span>纠错 </a></div><div class="lev3 toc-item"><a href="#模型方面的优化" data-toc-modified-id="模型方面的优化-136"><span class="toc-item-num">1.3.6&nbsp;&nbsp;</span>模型方面的优化 </a></div><div class="lev4 toc-item"><a href="#Softmax-优化：Hierarchical-Softmax" data-toc-modified-id="Softmax-优化：Hierarchical-Softmax-1361"><span class="toc-item-num">1.3.6.1&nbsp;&nbsp;</span>Softmax 优化：Hierarchical Softmax</a></div><div class="lev4 toc-item"><a href="#Softmax-优化：Noise-contrastive-estimation-(NCE)" data-toc-modified-id="Softmax-优化：Noise-contrastive-estimation-(NCE)-1362"><span class="toc-item-num">1.3.6.2&nbsp;&nbsp;</span>Softmax 优化：Noise-contrastive estimation (NCE)</a></div><div class="lev3 toc-item"><a href="#作业2" data-toc-modified-id="作业2-137"><span class="toc-item-num">1.3.7&nbsp;&nbsp;</span>作业 2</a></div><div class="lev4 toc-item"><a href="#纠错" data-toc-modified-id="纠错-1371"><span class="toc-item-num">1.3.7.1&nbsp;&nbsp;</span>纠错 </a></div><div class="lev2 toc-item"><a href="#循环神经网络" data-toc-modified-id="循环神经网络-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>循环神经网络 </a></div><div class="lev3 toc-item"><a href="#词向量的几种用法" data-toc-modified-id="词向量的几种用法-141"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>词向量的几种用法 </a></div><div class="lev3 toc-item"><a href="#如何阅读" data-toc-modified-id="如何阅读-142"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>如何阅读 </a></div><div class="lev3 toc-item"><a href="#建模" data-toc-modified-id="建模-143"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>建模 </a></div><div class="lev3 toc-item"><a href="#RNN-Demo-(Numpy)" data-toc-modified-id="RNN-Demo-(Numpy)-144"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>RNN Demo (Numpy)</a></div><div class="lev3 toc-item"><a href="#RNN-Demo-(Tensorflow)" data-toc-modified-id="RNN-Demo-(Tensorflow)-145"><span class="toc-item-num">1.4.5&nbsp;&nbsp;</span>RNN Demo (Tensorflow)</a></div><div class="lev3 toc-item"><a href="#分类-VS-Language-Model" data-toc-modified-id="分类-VS-Language-Model-146"><span class="toc-item-num">1.4.6&nbsp;&nbsp;</span>分类 VS Language Model</a></div><div class="lev3 toc-item"><a href="#RNN-Demo（处理变长数据）" data-toc-modified-id="RNN-Demo（处理变长数据）-147"><span class="toc-item-num">1.4.7&nbsp;&nbsp;</span>RNN Demo（处理变长数据）</a></div><div class="lev4 toc-item"><a href="#损失函数的解决" data-toc-modified-id="损失函数的解决-1471"><span class="toc-item-num">1.4.7.1&nbsp;&nbsp;</span>损失函数的解决 </a></div><div class="lev4 toc-item"><a href="#纠错" data-toc-modified-id="纠错-1472"><span class="toc-item-num">1.4.7.2&nbsp;&nbsp;</span>纠错 </a></div><div class="lev3 toc-item"><a href="#作业3" data-toc-modified-id="作业3-148"><span class="toc-item-num">1.4.8&nbsp;&nbsp;</span>作业 3</a></div>

# 循环神经网络

## Softmax 与交叉熵

- 神经网络语言模型
  - 用固定长度的上文预测下一个词
  - CNN：处理变化长度的句子，利用卷积神经网络的卷积层 +　maxpooling 变成固定长度的向量
  - RNN

### Sigmoid

$ Sigmoid + CE(Cross Entropy): C = -\frac {1}{n} \sum_{x}[yloga + (1-y)log(1-a)] $

- n 个样本
- x 加和，x 假设每个样本用 x 表示
- y 是 label
- a 是经过 Sigmoid 变换后的概率值（预测值），代表样本属于 1（正例）的概率；1-a 相反
- Sigmoid 只有一个输出 a

## 2-class Softmax

$ 2-class-Softmax + CE: C = -\frac {1}{n} \sum_{x}[y_1loga_1 + y_2loga_2] $

- a1 + a2 = 1
- y1, y2 对应的 label，一个是 1，另一个是 0
- 概率接近 1 时，越来越接近 0 ，取负号就是正数，但很小，cost 也很小；相反 cost 很大

### k-class Softmax

- 每个样本只有一个 label：  
  $ Softmax(k-class) + CE: C = -\frac {1}{n} \sum_{x} \sum_{k} [y_kloga_k] $

- 每个样本只有一个类别：
  - 只有一个 yk 是 1 其他都是 0
  - 对 cost 没有任何贡献
  - $ Softmax(k-class) + CE: C = -\frac {1}{n} \sum_{x} [y_{k=true}loga_{k=true}] $

- 每个样本给的是几个 label 上的概率分布：
  - y 变成概率值
  - `tf.nn.softmax_cross_entropy_with_logits` y 是概率分布
  - `tf.nn.sparse_softmax_cross_entropy_with_logits` sparse 意思是只有一个 label（二分类或者多分类），计算量更小，是上一个的特殊情况

## Word Embedding + Softmax 计算量

### FLOPs

- k：词向量维度
- V：词表大小
- 计算量：k × V 次浮点数乘法
- Forward + Backprop
- FLOPS 的概念：每秒做多少次浮点数计算  
  - CPU Frequency: 10^9 GHz, 10^6 MHz, 10^3 kHz
  - FLOPs per cycle \* Cores \* CPU Frequency: 2 \* 4 \* GHz

### FLOPs Code

In [1]:
import numpy as np
import time

In [3]:
batch_size = 1
vocab_size = 80000
word_embed = 128

In [4]:
# 导数第二层和最后一层
# 1 * 128
inputs = np.random.rand(batch_size, word_embed)
# 128 * 80000
weights = np.random.rand(word_embed, vocab_size)

In [8]:
start = time.time()
for i in range(100):
    inputs.dot(weights)
end = time.time()
print(end - start) / 100

0.00918579816818


In [7]:
%timeit inputs.dot(weights)

100 loops, best of 3: 8.44 ms per loop


In [6]:
# 平均每秒可以做多少次浮点数乘法
128 * 80000 / 0.009

1137777777.777778

理论值：2.20GHz × 4 × 2

In [13]:
# 实际/理论
1137777777.777778 / (2.2*(10**9) * 4 * 2), 1137777777.777778 / (2.2*(10**9) )

(0.06464646464646466, 0.5171717171717173)

### 评估/小结

- 可以估算模型时间下限（至少要多少时间）
- batch_size 增大，矩阵乘法会让耗时较小，但是性能红利随着矩阵 size 增大会递减（边际递减）
  - so，minibatch 是更好的选择：矩阵乘以矩阵性能红利（样本增加，需要消耗的时间不是等比例增加），而且算的更准
  - SGD：向量乘以矩阵
  - 集群：样本并行
      - 整体 batch_size 1000，10 台机器，每个机器**每次** 100 个样本
      - GPU FLOPs 非常高

### 作业1

测试你的 Language Model 在 batch_size = 1 VS batch_size = 125 时，预测完一定数量样本所需要的时间比（模型算出哪个词概率最高即可）

### Softmax 优化：降低 k 和 V

- 输出节点多的 Softmax 在 NLP 当中应用广泛
- 降低 k：深度 vs 宽度。和数据有关（问题简单降低也不会影响）
- 降低 V：字级别模型
  - 纯字级别：对应的 context 要拉长，k 也要增大
  - 字词混合：高频词用词级别，低频变成字级别

#### 纠错

- 视频2: 13:36 纯自己别 --> 纯字级别

### 模型方面的优化

#### Softmax 优化：Hierarchical Softmax



- 改进训练，没法改进【生成】
  - 只在最后用
  - 二叉树里，每个分支是一个 128 维的向量
  - 高频 label 走的路劲比较短
- 在 Google word2vec 中使用
  - 只需要拿到词向量

#### Softmax 优化：Noise-contrastive estimation (NCE)

- 对负例进行采样，转化成多个二分类问题
  - k 个负样本，k+1 个二分类问题
  - Eg  
      今天 星期 | 天  1  
      今天 星期 | 中国 0   
      今天 星期 | 厦门 0  
      今天 星期 | 哈哈 0  
- 理论上，实质损失函数和 Softmax 不一样了
  - k 负样本逐渐增加时，能够比较逼近 Softmax 损失函数
  - Mnih and Teh (2012): 25 个负样本，表现和 softmax 接近，提速 45 倍

### 作业2

使用一种方法改善 Lecture 4 中实现的神经网络语言模型的性能，并比较相对 Softmax 的训练性能提升

#### 纠错

视频2: 25:51 Noise-constranstive --> Noise-contranstive

## 循环神经网络

### 词向量的几种用法  

- 求平均：我喜欢你 vs 你喜欢我 | 北京到广州 vs 广州到北京
  - 对语义损害比较大
  - 因为都是用词向量处理语言模型、情感分类。求平均后无法区分，那模型相应也就没办法区分
- 卷积 + Pooling
  - 理论上可以区分两个相似的句子
- 循环神经网络（Recurrent neural network）
  - 可以处理变长的句子
  - 也可以区分相似的句子

### 如何阅读

一般来说是从左往后阅读一段文字

### 建模

- 模型的参数始终是同一组，只是 input 和 state 的变化
- 最基本的 RNN
- $new\_state = activation(W * input + U * state + B)$  
  - input 和 上一个 state 加 bias 

### RNN Demo (Numpy)

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# assume input and state are 128-length vector
class RNNCell:
    def __init__(self, input_size, state_size):
        self.W = np.random.rand(input_size, state_size)
        self.U = np.random.rand(state_size, state_size)
        self.b = np.zeros((1, state_size))
    def forward(self, input_, state):
        return input_.dot(self.W) + state.dot(self.U) + self.b

In [3]:
rnn = RNNCell(128, 128)

In [4]:
# 一个样本
input0 = np.random.rand(1, 128)

In [5]:
state0 = np.zeros((1, 128)) # 最初始的状态，全设为 0
state1 = rnn.forward(input0, state0)
print(state1.shape)

(1, 128)


In [6]:
input1 = np.random.rand(1, 128)
state2 = rnn.forward(input1, state1)
print(state2.shape)

(1, 128)


- 整个过程中，W, U, b 是没有变化的，在初始化中已经生成好了（假定是训练好的模型）
- 处理变长的句子，如情感分类

### RNN Demo (Tensorflow)

In [7]:
tf.reset_default_graph()

In [8]:
vocab_size = 100
word_embedding_dim = 128

In [9]:
cell = tf.contrib.rnn.BasicRNNCell(128)

In [10]:
cell

In [11]:
def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i: i + n]

In [12]:
data = np.asarray(list(chunks(range(30), 3)))

In [13]:
print(data)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


[0, 1, 2] 这个句子  
P(1|0) 以 0 为上下文预测下个词的分类问题  
P(2|(0, 1)) 0 1 作为上下文预测 2 这个词  

- RNN 情感分类只有最后一个 state 后面接了 Sigmoid 或者 Softmax
- RNN 做 Language Model，标准做法是每个 state 都会接个共享的 Softmax（当然中间还可以加其他隐层）。每个状态都有个自己的分类问题，预测这个状态下，下一个词是什么

In [14]:
word_embedding = tf.Variable(tf.random_uniform([vocab_size, word_embedding_dim]))
word_embedding
# 100 * 128

In [15]:
input_embeds = tf.nn.embedding_lookup(word_embedding, data[:, [0, 1]])
input_embeds
# 取第 0 1 列，前两个词的 index

<tf.Tensor 'embedding_lookup:0' shape=(10, 2, 128) dtype=float32>

In [16]:
# 这里 states 就是 output
# 也可以做更复杂的模型
# 本例中，前进了两步，会有两个输出，就是两个 state
# final state 和第二个 output 一样的
output, states = tf.nn.dynamic_rnn(cell, input_embeds, dtype=tf.float32)
print(output, states)

(<tf.Tensor 'rnn/transpose:0' shape=(10, 2, 128) dtype=float32>, <tf.Tensor 'rnn/while/Exit_2:0' shape=(?, 128) dtype=float32>)


In [17]:
# tensorflow 也可以 reshape
output_flat = tf.reshape(output, (-1, 128))

In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_val = output.eval()
    states_val = states.eval()
    
    print(output_flat.eval().shape) # 20*128
    print(output_val.shape) # 10*2*128
    # -1 让它自己算维度，也可以直接指定 20
    # 必须保证 reshape 后的形状和原来一样
    # 128 这个维度是不变的
    print(output_val.reshape((-1, 128)).shape) # 20*128
    
    print(states_val.shape) # 10*128
    
    print(output_val[:,1,:] == states_val)
    # 确定是不是每一个都是 True
    print((output_val[:,1,:] == states_val).all())

(20, 128)
(10, 2, 128)
(20, 128)
(10, 128)
[[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]]
True


- output_shape: 10 个样本，在 2 个 state 里各自的输出是怎样的
  - 之所以是 128 维是因为设置：`cell = tf.contrib.rnn.BasicRNNCell(128)`
- state_shape: evaluate 后的 value，只保存最后一个状态
- output: 取第二个状态（0 表示第一个，1 表示第二个），其他维度不变，看和最终的 state 是否一样
  - 根据前面所说，肯定一样，最后一个 output 和 state 是一样的
  - 并不是所有的 cell 都满足这样的假设，有的 output 和 state 是由不同的操作来完成，结果也会不太一样

### 分类 VS Language Model

- 假设做情感分类，目前长度都是 2（假设取 0 1 列），走了两步后，只要用最后的 state（10×128）作为后面正常前馈神经网络后续输入，再把对应的 label 和 cost 函数 对应的给它处理，就可以顺利完成分类问题
  - `labels = [[1, 2], [4, 5], [7, 8]]` 打平成 `labels_flat = [1, 2, 4, 5, 7, 8]` 就可以和 output 打平的结果对应
- Language Model，两个 output 都需要被用到
  - 10 个样本对应 20 个分类问题，每个样本有两个分类问题
  - 三维的 Tensor（10×2×128）转换成二维的（20×128) 20 个分类问题，就可以处理（Softmax）

### RNN Demo（处理变长数据）

In [19]:
# 三个样本，句子长度分别是 2 3 5
data = [[1, 2], [1, 2, 3], [1, 2, 3, 4, 5]]
data

[[1, 2], [1, 2, 3], [1, 2, 3, 4, 5]]

In [20]:
# padding，补 0
data_padding= np.asarray([[1, 2, 0, 0, 0], [1, 2, 3, 0, 0], [1, 2, 3, 4, 5]])
data_padding

array([[1, 2, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 2, 3, 4, 5]])

Padding 的问题：

- 因为后面有 0，RNN 进化到一个【不对】的状态
- 最长的句子可能很长，影响性能
- 损失函数没法安排，多了很多【假】label

In [21]:
tf.reset_default_graph()
vocab_size = 100
word_embedding_dim = 128

In [22]:
cell = tf.contrib.rnn.BasicRNNCell(128)
word_embedding = tf.Variable(tf.random_uniform([vocab_size, word_embedding_dim]))

In [28]:
# 去掉了最后一个词，对网络来说，不需要最后一个词
# 最后一个词作为 label 训练的
input_embeds = tf.nn.embedding_lookup(word_embedding, data_padding[:, 0:4])
input_embeds

<tf.Tensor 'embedding_lookup_1:0' shape=(3, 4, 128) dtype=float32>

In [29]:
print(data_padding[:, 0:4])

[[1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]


In [30]:
# 虽然给的数据是 padding 过的，但是 sequence_length 可以自动停止进化
# 它超过长度后，state 就一直复制上一个结果，output 就置为 0
# 只是简单复制，对性能影响也很小
output, states = tf.nn.dynamic_rnn(cell, input_embeds, dtype=tf.float32, sequence_length=[2, 3, 4])

- 加了 sequence_length 参数是一个 Tensor（可以随着 batch 的数据变化）  
- 对每个样本，超过其对应 sequence_length 之后，dynamic_rnn 不会实际去做 state 计算，而是直接复制上一个 state，超长的对应 output 则设置为 0 向量

#### 损失函数的解决

根据上面的解释我们知道可以让 dynamic_rnn 在超长之后不做实际计算，这时候超长的部分 output 会输出 0  
但是这些 output 仍然会和 label（非零部分才是真正的 label）进行计算，产生 cost，进而影响模型的变量  
所以要把 0 的部分的 label 在 cost 函数中去掉

In [64]:
data_padding[:, 1:5]

array([[2, 0, 0, 0],
       [2, 3, 0, 0],
       [2, 3, 4, 5]])

上面是我们这个 RNN Language Model 对应的 labels，我们如何让 0 的部分不计入损失呢？  

In [72]:
# label 在用之前会用 reshape 打平成固定长度的行向量
labels = tf.reshape(data_padding[:, 1:5], [-1])
labels

<tf.Tensor 'Reshape_2:0' shape=(12,) dtype=int64>

In [71]:
# >0 返回 1，否则 0
mask = tf.sign(labels)
mask

<tf.Tensor 'Sign_2:0' shape=(12,) dtype=int64>

In [79]:
mask = tf.sign([-2,1,0])

In [80]:
with tf.Session() as sess:
    print(mask.eval())

[-1  1  0]


把原来的 cost 和 mask 函数相乘，结果做 reduce_mean，作为新的 cost 给优化器进行优化，就把不想要的 label 置为 0，即可忽略这些无用的 labels，不会影响最后的 cost

#### 纠错

视频4: 6:20 mask 大于 0 返回 1 不是大于 0 返回 0 --> mask 大于 0 返回 1，小于 0 返回 -1, 0 返回 0


### 作业3

- 使用 RNN 构建语言模型，并进行生成，观察生成的效果
- 尝试学习并使用复杂度更高的 RNNCell，如 GRUCell，LSTMCell，并观察使用之后模型生成的效果