In [2]:
ls

neg_test.txt   pos_test.txt   w2_code.ipynb  w2_task.ipynb
neg_train.txt  pos_train.txt  w2_note.ipynb  w2_task_nice_sunoonlee.ipynb


## 自己用 Python 实现 Naive Bayes 方法，并在给定的数据集上验证效果

In [12]:
import jieba

In [33]:
import jieba.posseg as pseg

In [13]:
from collections import Counter

In [79]:
# 测试代码和数据
lm = Counter()
line_no = 0
limit = 1000

for line in open("neg_train.txt","r"):
    line_no += 1
    if line_no > limit:
        break
    words = pseg.cut(line.strip())
    
    for word, flag in words:
        if flag == 'x' or flag == 'uj' or flag == 'ul':
            continue
        lm[(word.encode('utf-8'), flag.encode('utf-8'))] += 1

In [82]:
for (word, flag),cnt in lm.most_common(10):
    print('%s %s %d' %(word, flag,cnt))

我 r 650
是 v 584
不 d 378
酒店 n 351
没有 v 301
就 d 287
在 p 272
也 d 266
房间 n 264
有 v 241


## 分析

### 训练集

In [773]:
lmp = Counter()
lmn = Counter()

for linep in open("pos_train.txt", "r"):
    wordsp = pseg.cut(linep.strip())
    
    for word, flag in wordsp:
        if flag == 'x' or flag == 'uj' or flag == 'ul':
            continue
        lmp[(word.encode('utf-8'), flag.encode('utf-8'))] += 1


for linen in open("neg_train.txt", "r"):
    wordsn = pseg.cut(linen.strip())

    for word, flag in wordsn:
        if flag == 'x' or flag == 'uj' or flag == 'ul':
            continue
        lmn[(word.encode('utf-8'), flag.encode('utf-8'))] += 1

In [774]:
sp = float(sum(lmp.values()))
for key, cnt in lmp.items():
    lmp[key] = (lmp[key]+1.0) / (sp + len(lmp))

In [775]:
sp, len(lmp)

(460008.0, 28273)

In [776]:
sn = float(sum(lmn.values()))
for key, cnt in lmn.items():
    lmn[key] = (lmn[key]+1.0) / (sn + len(lmn))

In [777]:
sn, len(lmn)

(410530.0, 22197)

In [778]:
for (word, flag),cnt in lmp.most_common(10):
    print('%s %s %f' %(word, flag,cnt))

是 v 0.018217
我 r 0.015106
也 d 0.010666
在 p 0.009339
有 v 0.008956
不错 a 0.008086
很 d 0.007844
都 d 0.007827
这 r 0.007182
很 zg 0.006849


In [779]:
for (word, flag),cnt in lmn.most_common(10):
    print('%s %s %f' %(word, flag,cnt))

是 v 0.018289
我 r 0.017568
不 d 0.011913
酒店 n 0.010471
也 d 0.008398
没有 v 0.008375
在 p 0.008148
就 d 0.007961
房间 n 0.007499
有 v 0.007282


In [780]:
traindict = {}

traindict = {"1":lmp, "0":lmn}

In [781]:
traindict['0'][('\xe6\x8a\xb1\xe6\x80\xa8', 'v')]

4.3907590698061365e-05

### 先验

In [593]:
npos = len(open("pos_train.txt", "r").readlines())

In [594]:
nneg = len(open("neg_train.txt", "r").readlines())

In [595]:
ppos = float(npos)/float(npos+nneg)
ppos

0.47112177662084115

In [596]:
pneg = 1 - ppos
pneg

0.5288782233791589

### 测试集

In [782]:
resultp = []

f = open('pos_test.txt', 'r')
for line in open("pos_test.txt"):
    line = f.readline()
    resultp.append(line)

In [783]:
len(resultp)

4965

In [784]:
resultn = []

f = open('neg_test.txt', 'r')
for line in open("neg_test.txt"):
    line = f.readline()
    resultn.append(line)

In [785]:
len(resultn)

5573

In [798]:
def cutSen(sen):
    sw = []
    s = pseg.cut(sen.strip())
    for word, flag in s:
        if flag == 'x' or flag == 'uj' or flag == 'ul':
            continue
        sw.append((word.encode('utf-8'), flag.encode('utf-8')))
    return sw

In [799]:
def rateWord(wf):
    
    wfs = cutSen(wf)
    
    import math
    rateps = 0
    ratens = 0
    for i in range(len(wfs)):
        wfp = traindict["1"][wfs[i]]
        wfn = traindict["0"][wfs[i]]
        
        if wfp == 0:
            ratep = math.log(1.0 / (sp + len(lmp) + 1.0))
        else:
            ratep = math.log(wfp)
        
        rateps += ratep
        
        if wfn == 0:
            raten = math.log(1.0/ (sn + len(lmn) +1.0))
        else:
            raten = math.log(wfn)
        
        ratens += raten
    
    return rateps + math.log(ppos), ratens + math.log(pneg)

In [800]:
testResultp = []

for i in range(len(resultp)):
    testResultp.append(rateWord(resultp[i]))

In [801]:
len(testResultp)

4965

In [802]:
n = 0
for i in range(len(testResultp)):
    if testResultp[i][0] > testResultp[i][1]:
        n += 1

In [803]:
n

3808

In [804]:
3808.0/4965

0.766968781470292

#### neg_test

In [805]:
testResultn = []

for i in range(len(resultn)):
    testResultn.append(rateWord(resultn[i]))

In [806]:
len(testResultn)

5573

In [807]:
n = 0
for i in range(len(testResultn)):
    if testResultn[i][0] < testResultn[i][1]:
        n += 1

In [808]:
n

4937

In [809]:
4937.0/5573

0.8858783420061008

### 相关概念

$P(y|S) = \frac{P(y,S)}{P(S)} = \frac{P(S|y)*P(y)}{P(S)}$  

$P(S|y=emotion) = P(w_1,w_2,...,w_n|y=emotion) \approx P(w_1|y=emotion)...P(w_n|y=emotion)$ 假设词之间独立

## 通过梯度下降方法，自己实现一种通用的给定数据找到 $y = wx + b$ 中最优 w 和 b 的程序，并用加噪音数据验证效果，和情感分析的关系？

### 梯度下降法推导：  

#### 主要观点

- 梯度下降法主要目的是找出最优的 w 和 b，基本思想是根据给定的 x 和 y 值，不断更新 w 和 b，将求得的 y 与给定的 y 值进行比较，选择离差平方和最小的 w 和 b

#### 实现步骤

- 设函数为：$$ h_\theta(x) = \theta_0 + \theta_1*x $$  
  写成矩阵形式（非常重要）：$$ h(x) = \sum_{i=0}^n \theta_ix_i $$
- 假设给定的 x', y' 分别为给定的值，求离差平方和为：$$ J(\theta_0, \theta_1) = \frac{1}{2m}\sum_{i=1}^m(h_\theta(x')-y')^2 $$
  乘以 1/2m 方便求导后化简。注意：这里的 m 表示 (x', y') 的个数，上式的 n 表示 $\theta$ 的个数

- 要求最小值，对离差平方和进行求导：$$ \frac{\partial}{\partial \theta_j} J(\theta_0, \theta_1) = \frac{1}{2m} \sum_{i=1}^m  \frac{\partial}{\partial \theta_j} (h_\theta(x')-y')^2 $$

j = 1 时：$$ \frac{\partial}{\partial \theta_j} J(\theta_0, \theta_1) = \frac{1}{m} \sum_{i=1}^m  (h_\theta(x')-y') * x' $$

j = 0 时：$$ \frac{\partial}{\partial \theta_j} J(\theta_0, \theta_1) = \frac{1}{m} \sum_{i=1}^m  (h_\theta(x')-y') $$

算法： 

Repeat {

  $$ \theta_0: = \theta_0 - \alpha \frac{1}{m} \sum_{i=1}^m  (h_\theta(x')-y') $$
  $$ \theta_1: = \theta_1 - \alpha \frac{1}{m} \sum_{i=1}^m  (h_\theta(x')-y')*x' $$
}

In [1]:
def g(x):
    
    return w*x + b

In [4]:
import numpy as np

In [91]:
def gradient(X, y, rate, eps, times):
    
    import numpy as np
    m = len(X)
    n = X.shape[1]   
    theta = np.array(np.zeros(n)).reshape(n,1)
    #x_train = np.column_stack((np.ones(m), x))
    x_train = X
    y_train = y.reshape(m, 1)
    Jcosts = []
    Jcost = 0
    Jcostt = 0

    for i in range(times):
        theta -= rate * ((x_train.dot(theta) - y_train) * x_train).sum(axis=0).reshape(n,1)
        Jcost = sum((x_train.dot(theta) - y_train) ** 2)/(2*m)
        Jcosts.append(Jcost)
        # 梯度下降!
        # 也可以直接 if Jcost < eps，但是不能避免 Jcost 永远无法收敛到 eps 大小的情况，
        # 所以需要找一个中间变量，用来做差，用 Jcost 的差作为判断循环停止的标准
        if abs(Jcost - Jcostt) < eps: 
            break
        #else:
        # 这里的 else 容易让人误会，可以不要，每次循环结束时，直接把 Jcost 赋给 Jcostt
        Jcostt = Jcost
    return theta, Jcosts

In [92]:
Y = 5 + 3 * x + np.random.random()

In [93]:
X = np.column_stack((np.ones(50), np.linspace(-10,10)))

In [97]:
gradient(X,Y,0.0001,0.0000001,1000)

(array([[ 5.0147646],
        [ 3.       ]]),
 [array([ 119.27133567]),
  array([ 85.35200291]),
  array([ 62.14129626]),
  array([ 46.24660329]),
  array([ 35.35024731]),
  array([ 27.86889707]),
  array([ 22.72089155]),
  array([ 19.16728719]),
  array([ 16.70326892]),
  array([ 14.98396721]),
  array([ 13.77377986]),
  array([ 12.91175095]),
  array([ 12.28791946]),
  array([ 11.82716168]),
  array([ 11.47815316]),
  array([ 11.20582801]),
  array([ 10.98622747]),
  array([ 10.80298067]),
  array([ 10.64490046]),
  array([ 10.504341]),
  array([ 10.37607574]),
  array([ 10.25653091]),
  array([ 10.14326186]),
  array([ 10.03459537]),
  array([ 9.92938521]),
  array([ 9.82684521]),
  array([ 9.72643524]),
  array([ 9.62778322]),
  array([ 9.53063199]),
  array([ 9.43480283]),
  array([ 9.34017073]),
  array([ 9.24664732]),
  array([ 9.15416936]),
  array([ 9.06269074]),
  array([ 8.97217716]),
  array([ 8.88260232]),
  array([ 8.79394551]),
  array([ 8.7061898]),
  array([ 8.61932089

In [98]:
x = np.array([(1, 0., 3),(1, 1., 3),(1, 2., 3),(1, 3., 2), (1, 4, 4)])
y = np.array([95.364, 97.217205, 75.195834, 60.105519, 49.342380])
y = y.reshape(5,1)

In [99]:
x

array([[ 1.,  0.,  3.],
       [ 1.,  1.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  3.,  2.],
       [ 1.,  4.,  4.]])

In [100]:
y

array([[ 95.364   ],
       [ 97.217205],
       [ 75.195834],
       [ 60.105519],
       [ 49.34238 ]])

In [110]:
gradient(x,y,0.01,0.0001,10000) # 实际 2277 次即收敛

(array([[ 97.00064027],
        [-13.02096252],
        [  1.48125573]]),
 [array([ 768.7782964]),
  array([ 577.29270693]),
  array([ 518.92576552]),
  array([ 474.55103067]),
  array([ 436.13282235]),
  array([ 402.53270587]),
  array([ 373.11659378]),
  array([ 347.35284277]),
  array([ 324.77856753]),
  array([ 304.98965507]),
  array([ 287.63323526]),
  array([ 272.40117872]),
  array([ 259.02442378]),
  array([ 247.26802288]),
  array([ 236.92681716]),
  array([ 227.82165945]),
  array([ 219.79611612]),
  array([ 212.71358723]),
  array([ 206.45479168]),
  array([ 200.91557135]),
  array([ 196.00497357]),
  array([ 191.64357679]),
  array([ 187.76202851]),
  array([ 184.29976856]),
  array([ 181.20391434]),
  array([ 178.42828735]),
  array([ 175.93256311]),
  array([ 173.68152898]),
  array([ 171.64443598]),
  array([ 169.79443284]),
  array([ 168.10807178]),
  array([ 166.564877]),
  array([ 165.14696786]),
  array([ 163.83872981]),
  array([ 162.62652708]),
  array([ 161.49845

### 网上参考的代码

In [7]:
x = np.array([(1, 0., 3),(1, 1., 3),(1, 2., 3),(1, 3., 2), (1, 4, 4)])
y = np.array([95.364, 97.217205, 75.195834, 60.105519, 49.342380])
y = y.reshape(5,1)

epsilon = 0.0001

# 学习率
alpha = 0.01
diff = [0, 0]
max_itor = 1000
error1 = 0
error0 = 0
cnt = 0
m = len(x)
errors = []

# 初始化参数
theta = np.array([0, 0, 0]).reshape(3,1)

while True:
    cnt += 1

    # 参数迭代计算
    for i in range(m):
        theta = theta - alpha * ((x.dot(theta) - y) * x).sum(axis=0).reshape(3,1)
    # 计算损失函数
    #error1 = 0
    #for lp in range(len(x)):
    error1 += sum((x.dot(theta) - y) ** 2)/(2*m)
    errors.append(error1)

    if abs(error1-errors[-1]) < epsilon:
        break
#    else:
#        error0 = error1

    print ' theta0 : %f, theta1 : %f, theta2 : %f, error1 : %f' % (theta[0], theta[1], theta[2], errors[-1])
#print 'Done: theta0 : %f, theta1 : %f, theta2 : %f' % (theta0, theta1, theta2)
#print '迭代次数: %d' % cnt